sudo: required
services:
  - docker
env:
  global:
    - IMAGE_NAME=dchui1/ci_tutorial
    # - REGISTRY_USER=myrobot
    # REGISTRY_PASS=...
    - secret: "<something long>"
language: python
python:
  - "3.5"

# command to install dependencies
install:
  - pip install -r requirements.txt
before_script:
  - docker pull $IMAGE_NAME || true
# command to run tests
script:
  - pytest
  - docker build --pull --cache-from "$IMAGE_NAME" --tag "$IMAGE_NAME" .

deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${version}"
  on:
    branch: master
