sudo: required
language: python
python:
  - "3.5"

install:
  - pip install -r requirements.txt

# browser source
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable

# install browser and driver
before_script:
  gem install chromium
  - sudo chmod u+x chromedriver
  - sudo mv chromedriver /usr/bin/
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5

script:
  - pytest